version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: chess_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: chess
      POSTGRES_PASSWORD: chess_pass
      POSTGRES_DB: chess_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: chess_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  pgdata: